spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  # Configuration to fetch details from eureka service registryy
  # The gateway service uses configuration from eureka to forward
  # request from clients to microservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: Eazy Bank Gateway Server Application
    version: 1.0.0
logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG